# Generated by Django 4.2.9 on 2024-01-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_db_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='details',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
